In [7]:
import numpy as np

def print_numpy_attributes(a):
    """dumps ``numpy.ndarray`` attribute information 
    
    :param a: 
    :type a: np.ndarray 
    :return: 
    """
    print('', a)  # data will be printed. this is same with a.data
    print('type', type(a))  # should be <class 'numpy.ndarray'>
    print('data', a.data)   # actual array data
    print('dtype', a.dtype)  # type of data (int, float32 etc)
    print('shape', a.shape)  # dimensional information of data (2, 3) etc.
    print('ndim', a.ndim)  # total dimension of shape. 0 means scalar, 1 is vector, 2 is matrix... 
    print('size', a.size)  # total size of data, which is product sum of shape
        
    
# 1. creating scalar
l1 = 3
a1 = np.array(l1)  # note that np.array([3]) will create vector with 1 element
print(l1, type(l1))
print_numpy_attributes(a1)


# 2. creating vector
l2 = [1, 2, 3]
print(l2, type(l2))
a2 = np.array(l2)
print(a2, type(a2), a2.dtype, a2.shape)

# 3. creating matrix
l3 = [[1, 2, 3], [4, 5, 6]]
a3 = np.array(l3)
print(l3, type(l3))
print(a3, type(a3), a3.dtype, a3.shape, a3.ndim, a3.size)

# 4. creating general multi-dimensional array (tensor)
a4 = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[11, 22, 33], [44, 55, 66]]
    ]
)
print(a4, type(a4), a4.dtype, a4.shape, a4.ndim, a4.size)

3 <class 'int'>
 3
type <class 'numpy.ndarray'>
data <memory at 0x0000019ABAB15A20>
dtype int32
shape ()
ndim 0
size 1
[1, 2, 3] <class 'list'>
[1 2 3] <class 'numpy.ndarray'> int32 (3,)
[[1, 2, 3], [4, 5, 6]] <class 'list'>
[[1 2 3]
 [4 5 6]] <class 'numpy.ndarray'> int32 (2, 3) 2 6
[[[ 1  2  3]
  [ 4  5  6]]

 [[11 22 33]
  [44 55 66]]] <class 'numpy.ndarray'> int32 (2, 2, 3) 3 12
